version: '3.1'
services:
  db:
    build: ./postgresql
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_DB: WebsiteDatabase
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
    secrets:
      - postgres-passwd
  website:
    build: ./website
    restart: always
    ports:
      - "8000:80" #host/container
    depends_on:
      - db
secrets:
   postgres-passwd:
     file: db_password.txt

